# This is a basic workflow to help you get started with Actions

name: check-staged

# Controls when the workflow will run
on:
  push:
    branches:
     - '**'
  pull_request:
    branches:
     - '**' 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Print branch name
        shell: bash
        run: echo "::set-output name=brunch::${{ steps.extract_branch.outputs.branch }}"
