# This is a basic workflow to help you get started with Actions

name: check-staged

on:
  push:
    branches:
     - '**'
  pull_request:
    branches:
     - '!master' 
     - '!staging'
jobs:

  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch origin
          BRANCH=$(echo ${GITHUB_REF#refs/heads/})
          UNSTAGED=$(git branch -r --no-merged origin/staging | grep "${BRANCH}")
          echo "::set-output name=staged::$([ -z ${UNSTAGED} ] && echo 'true' || echo 'false')"
        id: staging_check
      - uses: ouzi-dev/commit-status-updater@v1.1.0
        with:
          name: staged
          status: "${{ steps.staging_check.outputs.staged }}"  
          
      
      
