# This is a basic workflow to help you get started with Actions

name: check-staged

on:
  push:
    branches:
     - '**'
  pull_request:
    branches:
     - '!master' 
     - '!staging'
jobs:

  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch origin
          BRANCH=$(echo ${GITHUB_REF#refs/heads/})
          STAGED=$(git branch -r --no-merged origin/staging | grep "${BRANCH}")
          echo "::set-output name=staged::$([ -z ${STAGED} ] && echo 'false' || echo 'true'"
          
      
      
