# This is a basic workflow to help you get started with Actions

name: check-staged

on:
  push:
    branches:
      - 'staging'

  workflow_dispatch:     
  
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
  
jobs:

  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |          
          STAGED="$(git branch -r --merged origin/staging)"          
          RELEASED="$(git branch -r --merged origin/master)"
          CURRENTLY_STAGED="$(comm -23 <(echo "$STAGED") <(echo "$RELEASED"))"
          while IFS= read -r FB; do
            if [[ "${FB}" != "origin/staging" ]]; then
              echo "updating status of $FB"
              curl \
              --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
              --header "Content-Type: application/json" \
              --data '{"state": "success", "context": "staged"}' \
              --request POST \
              "https://api.github.com/repos/dboyce/glowing-octo-happiness/statuses/$(git rev-list -n 1 $FB)"
            fi  
          done <<< "$CURRENTLY_STAGED"
        shell: bash
