# This is a basic workflow to help you get started with Actions

name: check-staged

on:
  push:
    branches:
      - 'staging'

  workflow_dispatch:     
  
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
  
jobs:

  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch origin
          git checkout master
          git checkout staging
          STAGED="$(git branch -r --merged staging)"          
          RELEASED="$(git branch -r --merged master)"
          CURRENTLY_STAGED="$(comm -23 <(echo "$STAGED") <(echo "$RELEASED"))"
          echo "currently staged ${STAGED} released ${RELEASED}"
          while IFS= read -r FB; do
            echo "updating status of $FB"
            #curl \
           #--header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
           #--header "Content-Type: application/json" \
           #--data '{"state": "success", "context": "staged"}' \
           #--request POST \
           #  "https://api.github.com/repos/dboyce/glowing-octo-happiness/statuses/$(git rev-list -n 1 $FB)"
          done <<< "$CURRENTLY_STAGED"
        shell: bash
