# This is a basic workflow to help you get started with Actions

name: check-staged

on:

  pull_request:
    branches:
     - '!master' 
     - '!staging'

  workflow_dispatch:     
  
jobs:

  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch origin
          echo "$(git branch -r)"
          BRANCH=$(echo ${GITHUB_REF#refs/heads/})
          UNSTAGED=$(git branch -r --no-merged origin/staging | grep "${BRANCH}")
          if [[ -n "${UNSTAGED}" ]]; then
            echo "::set-output name=message::${BRANCH} not merged to staging"
            exit 1;
          fi


      
      
