# This is a basic workflow to help you get started with Actions

name: check-staged

on:
  push:
    branches:
      - 'staging'

  workflow_dispatch:     
  
jobs:

  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch origin
          STAGED="$(git branch -r --merged origin/staging | sort)"
          RELEASED="$(git branch -r --merged origin/master | sort)"
          CURRENTLY_STAGED="$(comm -23 <(echo "$STAGED") <(echo "$RELEASED"))"
          while IFS= read -r FB; do
            echo "the feature branch ${FB} is currently in staging"
          done <<< "$CURRENTLY_STAGED"
        id: staging_check
